### PR TITLE
Using withEnv instead of modifying env.PATH

### PR DESCRIPTION
**Pull request by batmat**
Modified to use `withEnv` instead as advised by @daniel-beck and @jglick in https://github.com/jenkinsci/pipeline-examples/pull/15.

### CODE REVIEW

**Comment by ssbarnea** [comment]
@abayer can you please enable issue tracker on this repository so we can raise bugs regarding existing examples or even add tickets for missing examples that have to be implemented?

I would like to contribute with new examples but before implementing them I want to have tickets. It does not make any sense to have different people implementing the same feature in parallel.  Thank you.

**Comment by batmat** [comment]
@ssbarnea In general, we don't enable GH issues for a reason. We use http://issues.jenkins-ci.org/ for all the Jenkins project issues.
Though I admit I'm a bit less certain about this very repo, as using Jenkins issues for pipeline examples might be overkill / not of great values among the general plugin and Jenkins core issues.
Or maybe still in the JIRA, but using some documentation tag or something?

WDYT @daniel-beck @rtyler @abayer ?

**Comment by ssbarnea** [comment]
I use Jira with GitHub at work too for the same reasons as Jenkins project. Still, there are cases where using Jira issue tracker could be an overkill. In case of this repo it could also deter some contributors as they would have to eventually create a jira account and figure out how to navigate in it (not really obvious, as we know)

As I have a strong interest in documenting the pipelines, I could take care of this repository, dealing with issues and PRs.

**Comment by ssbarnea** [comment]
I use Jira with GitHub at work too for the same reasons as Jenkins project. Still, there are cases where using Jira issue tracker could be an overkill. In case of this repo it could also deter some contributors as they would have to eventually create a jira account and figure out how to navigate in it (not really obvious, as we know)

As I have a strong interest in documenting the pipelines, I could take care of this repository, dealing with issues and PRs.

**Pull request merged**
