### PR TITLE
Add ssh-agent usage example

### PR DESCRIPTION
**Pull request by orevial**
Just added a small example of ssh-agent usage for Git push

### CODE REVIEW

**Comment by daniel-beck** [comment]
Is `git-credentials` the ID of these credentials? If so, should be made explicit (or show a UUID instead to be super clear it's an ID).

**Comment by orevial** [comment]
Yes it is the ID of the SSH credentials. What would you put as the credentials ID ? "git-ssh-UUID" ? Tell me and I'll change the code accordingly.

**Comment by daniel-beck** [comment]
Well, `git-credentials-ID` would be a solid improvement already. Change the previous use (`credentialsId: MyID`) accordingly for consistency and it should be clear enough IMO.

**Comment by orevial** [comment]
Hmm I'm not sure we want to use the same Id in both examples because it could be confusing to read twice the same Id for different use cases (username/password and SSH)

**Comment by orevial** [comment]
I've modified both credentialsId, I'll let you judge if that's fine for you.

**Comment by daniel-beck** [comment]
@orevial Thank you!

**Pull request merged**
