### PR TITLE
Deleting obsolete advice

### PR DESCRIPTION
**Pull request by jglick**
Not true for a while.

@reviewbybees

### CODE REVIEW

**Comment by dqwork** [comment]
hello! So I've been digging around some old stackoverflow answers and other forum posts etc, for a solution to my problem.

I can't do myMap.each { echo $it } in my pipeline... however I see that this commit removed advice about handling the fact jenkins couldn't do this. Which implies it now can...but that doesn't seem to be the case?

**Comment by jglick** [comment]
`Map.each(Closure)` ought to work, for years now.

**Comment by dqwork** [comment]
Thanks for getting back to me so quickly, wasn't expecting that for an issue so old.

Turns out, probably unsurprisingly, this was an issue in my code. Groovy isn't my day to day language so I made a bit of a rookie mistake in the pipeline code. I was referring to the closure variable `it` as `$it` outside of interpolated strings ( I could try and blame the website with the examples I read but its def my fault 😄 ) once I corrected that it works. 

You're quick response prompted me to recheck and thats when I noticed it, so thank you again

**Comment by jglick** [comment]
Glad that helped!

**Pull request merged**
